install! 'cocoapods', :generate_multiple_pod_projects => false
platform :ios, '14.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', :debug => :debug, :profile => :profile, :release => :release

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # 只保留最基础的 Flutter 引用，彻底删掉 require podhelper 那行
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end